/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class juniorjar35_sunflower3d_Utils_Utils */

#ifndef _Included_juniorjar35_sunflower3d_Utils_Utils
#define _Included_juniorjar35_sunflower3d_Utils_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     juniorjar35_sunflower3d_Utils_Utils
 * Method:    getCpuBrandString0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_juniorjar35_sunflower3d_Utils_Utils_getCpuBrandString0
  (JNIEnv *, jclass);

/*
 * Class:     juniorjar35_sunflower3d_Utils_Utils
 * Method:    getCpuVendorString0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_juniorjar35_sunflower3d_Utils_Utils_getCpuVendorString0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
